name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x86, x64] # 定义32位和64位架构

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up MSVC environment
    - name: Set up MSVC for Windows
      shell: cmd
      run: |
        if "%matrix.architecture%" == "x64" (
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
        ) else (
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
        )

    # Step 3: Install dependencies
    - name: Install libcurl
      run: |
        choco install curl -y

    # Step 4: Build the project for each architecture
    - name: Build
      run: |
        cl /EHsc /std:c++17 src\main.cpp /Iinclude /Fe:build\main_%matrix.architecture%.exe /link iphlpapi.lib ws2_32.lib wldap32.lib advapi32.lib

    # Step 5: Run the application (optional, only for validation)
    - name: Run application (optional)
      run: |
        build\main_%matrix.architecture%.exe
