name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install dependencies
      run: choco install curl -y

    - name: Build project
      shell: cmd
      run: |
        msbuild src\main.cpp /p:Configuration=Release /p:Platform=%matrix.architecture%

    - name: Run executable (optional)
      run: |
        build\main_%matrix.architecture%.exe
