name: Build and Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Compile the program using cl.exe
      - name: Compile Program
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.architecture }}
          cl /EHsc /O2 /MT src\main.cpp /Iinclude /link /OUT:main-${{ matrix.architecture }}.exe

      # Step 3: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MySoftware-${{ matrix.architecture }}
          path: main-${{ matrix.architecture }}.exe
