name: Build C++ Project on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x86, x64] # 编译 32 位和 64 位

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装必要的构建工具
      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install mingw -y
          choco install curl -y
          $Env:Path += ";C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          $Env:Path += ";C:\ProgramData\chocolatey\lib\curl\tools\curl-7.87.0-win64-mingw\include"

      # 配置和编译
      - name: Configure and Build
        shell: cmd
        run: |
          mkdir build
          cd build
          if "%{{ matrix.arch }}"=="x86" (
            cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_EXE_LINKER_FLAGS="-L'C:/ProgramData/chocolatey/lib/curl/tools/curl-7.87.0-win64-mingw/lib'" ..
          ) else (
            cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_EXE_LINKER_FLAGS="-L'C:/ProgramData/chocolatey/lib/curl/tools/curl-7.87.0-win64-mingw/lib'" ..
          )
          mingw32-make

      # 上传编译的可执行文件作为 Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.arch }}
          path: build\your_executable_name.exe # 替换为生成的可执行文件路径
