name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    strategy:
      matrix:
        architecture:
          - Win32
          - x64 # 直接指定平台名称

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install -y visualstudio2022buildtools
        choco install -y visualstudio2022-workload-vctools

    - name: Configure and Build
      shell: cmd
      run: |
        echo Configuring and building for architecture: ${{ matrix.architecture }}
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} ..
        cmake --build . --config Release
