name: Build C++ Program

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 MinGW 和 MinGW 的 libcurl 开发包
      - name: Install MinGW and libcurl
        run: |
          choco install mingw -y
          pacman -S mingw-w64-x86_64-curl mingw-w64-x86_64-curl-dev --noconfirm

      # 3. 配置 PATH
      - name: Configure PATH
        run: echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH

      # 4. 编译 32 位可执行文件
      - name: Compile 32-bit Executable
        run: |
          g++ -I"C:\tools\mingw64\include" -L"C:\tools\mingw64\lib" -m32 -o program32.exe main.cpp -lcurl -lws2_32 -liphlpapi -std=c++17

      # 5. 编译 64 位可执行文件
      - name: Compile 64-bit Executable
        run: |
          g++ -I"C:\tools\mingw64\include" -L"C:\tools\mingw64\lib" -m64 -o program64.exe main.cpp -lcurl -lws2_32 -liphlpapi -std=c++17

      # 6. 上传编译结果
      - name: Upload Executables
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executables
          path: |
            program32.exe
            program64.exe
