name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: lukka/get-cmake@v3

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install curl

    - name: Configure project
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run Tests (if any)
      run: ./build/bin/MyApp
