name: Build C++ Program

on:
  push:
    branches:
      - main  # 监听推送到 main 分支
  pull_request:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 MinGW（Windows GCC 工具链）
      - name: Install MinGW
        run: choco install mingw -y

      # 3. 配置 PATH 环境变量（确保 g++ 可用）
      - name: Configure PATH for MinGW
        run: |
          echo "::add-path::C:\tools\mingw64\bin"

      # 4. 编译 32 位可执行文件
      - name: Compile 32-bit Executable
        run: |
          g++ -m32 -o program32.exe main.cpp -lcurl -lws2_32 -liphlpapi -std=c++17

      # 5. 编译 64 位可执行文件
      - name: Compile 64-bit Executable
        run: |
          g++ -m64 -o program64.exe main.cpp -lcurl -lws2_32 -liphlpapi -std=c++17

      # 6. 上传编译结果
      - name: Upload Executables
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executables
          path: |
            program32.exe
            program64.exe
