name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_32_and_64:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install Dependencies
        run: |
          choco install curl
          choco install mingw

      - name: Create Build Directory
        run: |
          mkdir build-%arch%

      - name: Configure CMake
        run: |
          cmake -S . -B build-%arch% -A %arch%
        working-directory: ${{ github.workspace }}

      - name: Build with CMake
        run: |
          cmake --build build-%arch%
        working-directory: ${{ github.workspace }}

      - name: Run Tests
        run: |
          cd build-%arch%
          ./CardVerificationApp
        working-directory: ${{ github.workspace }}
