name: Windows C++ Build

on:
  push:
    branches:
      - main  # 监听 main 分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 构建环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码库

    - name: Set up MSVC environment and build
      run: |
        cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && mkdir build && cl.exe /EHsc /Iinclude /D _WIN32 main.cpp /link /OUT:build\my_program.exe"

    - name: Run the compiled program
      run: |
        build\my_program.exe
