name: Build C++ Program

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 MinGW（Windows GCC 工具链）
      - name: Install MinGW
        run: choco install mingw -y

      # 3. 安装 libcurl（带开发文件）
      - name: Install libcurl
        run: choco install curl -y

      # 4. 配置 PATH 和 Include 路径
      - name: Configure PATH and Curl Includes
        run: |
          echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH
          echo "C:\tools\curl\include" >> $env:GITHUB_PATH

      # 5. 编译 32 位可执行文件
      - name: Compile 32-bit Executable
        run: |
          g++ -I"C:\tools\curl\include" -L"C:\tools\curl\lib" -m32 -o program32.exe main.cpp -lcurl -lws2_32 -liphlpapi -std=c++17

      # 6. 编译 64 位可执行文件
      - name: Compile 64-bit Executable
        run: |
          g++ -I"C:\tools\curl\include" -L"C:\tools\curl\lib" -m64 -o program64.exe main.cpp -lcurl -lws2_32 -liphlpapi -std=c++17

      # 7. 上传编译结果
      - name: Upload Executables
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executables
          path: |
            program32.exe
            program64.exe
