name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build EXE
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup vcpkg
      uses: microsoft/vcpkg-action@v2
      with:
        vcpkgGitCommitId: 2023.06.23 # 固定版本，确保一致性

    - name: Install Dependencies
      run: vcpkg install curl:x64-windows

    - name: Install MinGW
      run: choco install mingw -y
      shell: cmd

    - name: Add MinGW to Path
      run: echo "C:\Program Files\mingw-w64\mingw64\bin" >> $env:GITHUB_PATH
      shell: powershell

    - name: Build Project
      run: |
        g++ -std=c++17 -Iinclude -o software.exe main.cpp -lws2_32 -liphlpapi -lcurl
        dir
      shell: cmd

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: compiled-exe
        path: software.exe
