name: Windows C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build the project
      run: |
        mkdir build
        cl.exe /EHsc /Iinclude /D "_WIN32" main.cpp /link /OUT:build\my_program.exe

    - name: Run the compiled program (optional)
      run: build\my_program.exe
