name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build EXE
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install Dependencies
      run: .\vcpkg\vcpkg.exe install curl:x64-windows

    - name: Install MinGW
      run: choco install mingw -y
      shell: cmd

    - name: Add MinGW to Path
      run: echo "C:\Program Files\mingw-w64\mingw64\bin" >> $env:GITHUB_PATH
      shell: powershell

    - name: Build Project
      run: |
        g++ -std=c++17 -Iinclude -o software.exe main.cpp -L.\vcpkg\installed\x64-windows\lib -lws2_32 -liphlpapi -lcurl
        dir
      shell: cmd

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: compiled-exe
        path: software.exe
