name: C++ Build and Test

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当创建针对 main 分支的 PR 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码库
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装必需的依赖项
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ libcurl4-openssl-dev

    # 创建构建目录并编译项目
    - name: Build the project
      run: |
        mkdir -p build
        g++ -std=c++17 -o build/my_program main.cpp -lcurl -lpthread

    # 运行编译后的程序（可选）
    - name: Run the compiled program (Optional)
      run: |
        ./build/my_program
