name: Build C++ Project on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装必要的构建工具
      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install mingw -y
          choco install curl -y
          $Env:Path += ";C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"

      # 配置和编译
      - name: Configure and Build
        shell: cmd
        run: |
          mkdir build
          cd build
          if "%{{ matrix.arch }}"=="x86" (
            cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_CXX_FLAGS="-m32" ..
          ) else (
            cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_CXX_FLAGS="-m64" ..
          )
          mingw32-make

      # 上传编译的可执行文件作为 Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.arch }}
          path: build\your_executable_name.exe
