name: Build and Package (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        # 安装 Chocolatey 和必要依赖
        choco install -y curl       # 安装 curl
        choco install -y cmake      # 安装 CMake
        choco install -y mingw      # 安装 MinGW 编译器

    - name: Download and Setup libcurl
      run: |
        # 下载预编译的 libcurl (Windows MSVC 版本)
        curl -LO https://curl.se/windows/dl-7.x.x/curl-7.x.x-win64-msvc.zip
        mkdir C:\curl
        tar -xf curl-7.x.x-win64-msvc.zip -C C:\curl --strip-components=1

    - name: Configure CMake
      run: |
        # 配置 CMake 项目，并指定 libcurl 的路径
        cmake -S . -B build -G "Visual Studio 17 2022" ^
          -DCURL_INCLUDE_DIR=C:/curl/include ^
          -DCURL_LIBRARIES=C:/curl/lib/libcurl.lib

    - name: Build project
      run: cmake --build build --config Release

    - name: Package output
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-windows
        path: build/Release/MyApp.exe # 上传可执行文件
