name: Build C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86, x64] # 编译 32 位和 64 位

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装必要的构建工具
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++-multilib make cmake curl

      # 配置和编译
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.arch }}" == "x86" ]; then
            cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-m32" ..
          else
            cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-m64" ..
          fi
          make

      # 上传编译的可执行文件作为 Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.arch }}
          path: build/your_executable_name # 替换为生成的可执行文件路径
