name: Build for Windows (32-bit and 64-bit)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x86, x64] # Compile for 32-bit and 64-bit

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install MinGW via Chocolatey
    - name: Install MinGW
      run: |
        choco install mingw -y
        if (${{ matrix.architecture }} == 'x64') {
          $env:PATH="C:\tools\mingw64\bin;$env:PATH"
        } else {
          $env:PATH="C:\tools\mingw32\bin;$env:PATH"
        }
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Process)

    # Verify GCC installation
    - name: Verify GCC installation
      run: |
        g++ --version

    # Build the project
    - name: Build application
      run: |
        mkdir -p build
        cd build
        g++ -std=c++17 ../main.cpp -o app-${{ matrix.architecture }}.exe -I../include -lcurl -liphlpapi

    # Upload the artifacts (compiled binaries)
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-app-${{ matrix.architecture }}
        path: build/app-${{ matrix.architecture }}.exe
