name: Build and Package (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and Setup libcurl
      run: |
        # 下载预编译的 libcurl (Windows MSVC 版本)
        curl -LO https://curl.se/windows/dl-7.92.0/curl-7.92.0-win64-mingw.zip
        mkdir C:\curl
        # 使用 PowerShell 解压
        powershell -Command "Expand-Archive -Path curl-7.92.0-win64-mingw.zip -DestinationPath C:\curl"

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" ^
          -DCURL_INCLUDE_DIR=C:/curl/include ^
          -DCURL_LIBRARIES=C:/curl/lib/libcurl.lib

    - name: Build project
      run: cmake --build build --config Release

    - name: Package output
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-windows
        path: build/Release/MyApp.exe
